language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"

install:
  - pip install coveralls pytest coverage mock pytest-cov
  - pip install -r requirements.pip

script:
  py.test --cov-report xml --cov-report html --junitxml=pytest.xml --cov-config=tests/.coveragerc -vv --cov sample_data_utils

after_success:
  - coveralls
